spring:
  application:
    name: service-card
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    stream:
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}
#
server:
  port: 0
#
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_URL}
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
#
management:
  endpoints:
    web:
      exposure:
        include: '*'
#
#logging:
#  file:
#    name: ./logs/log-file.log
#
mq:
  queues:
    cards-emit: cards-emit
