spring:
  application:
    name: service-discovery
  security:
    user:
      name: ${DISCOVERY_USERNAME}
      password: ${DISCOVERY_PASSWORD}
#
server:
  port: 8761
#
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
